# values.yaml

ipAddressPools:
  - name: first-pool
    namespace: metallb-system
    addresses:
      - 192.168.1.240-192.168.1.250

l2Advertisements:
  - name: first-pool-advertisement
    namespace: metallb-system
    ipAddressPools:
      - first-pool
